config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    root to: "homes#top"
    get "home/about"=>"homes#about"
    resources :items, only: [:index, :show]
    get "customers/my_page"=>"customers#show"
    get "customers/information/edit"=>"customers#edit"
    patch "customers/information"=>"customers#update"
    get "customers/unsubscribe"=>"customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do 
        get "complete"
        post "confirm"
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit_card: 0,
    transfer: 1 
  }

  enum status: {
    waiting_for_payment: 0, # 入金待ち (デフォルト)
    payment_confirmed: 1,   # 入金確認
    in_production: 2,       # 製作中
    ready_to_ship: 3,       # 製作完了
    shipped: 4              # 発送済み
  }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :name, format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]{2,20}\z/, message: 'は２文字以上の全角のひらがな、カタカナ、漢字のみで入力してください。' }
  validates :postal_code, format: { with: /\A\d{7}\z/, message: 'は7桁の半角数字のみで入力してください。' }
  validates :address, presence: true, length: { maximum: 255 }
  validates :payment_method, presence: true


  def subtotal
    item.with_tax_price * amount
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_order, only: [:update, :show]

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == "payment_confirmed"
        @order.order_details.update_all(making_status: :not_started)
      end
      redirect_to admin_order_path(@order), notice: "変更が保存されました"
    else
      render :show
    end
  end
    
  def show
    @order = Order.find(params[:id])
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:status)
    end

    def update_order_status
      @order.status ||= :waiting_for_payment
      if @order.order_details.all? { |detail| detail.completed? }
        @order.update(status: :ready_to_ship)
      elsif @order.order_details.any? { |detail| detail.in_production? }
        @order.update(status: :in_production)
      end
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="mt-3 mb-5 ml-3 text-left">
  <h2>注文履歴詳細</h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><strong>購入者</strong></td>
              <td>
                <%= link_to "#{@order.customer.last_name} #{@order.customer.first_name}", admin_customer_path(@order.customer), class: "text-decoration-none" %>
              </td>
            </tr>
            <tr>
              <td><strong>注文日</strong></td>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <td><strong>配送先</strong></td>
              <td>〒<%= @order.postal_code %>&nbsp;&nbsp;<%= @order.address %><br>
                  <%= @order.name %>
              </td>
            </tr>
            <tr>
              <td><strong>支払い方法</strong></td>
              <td><%= I18n.t(@order.payment_method, scope: ["enums", "order", "payment_method"]) %></td>
            </tr>
            <tr>
              <td><strong>注文ステータス</strong></td>
              <td>
                <div class="d-flex align-items-center">
                  <%= f.select :status, Order.statuses.keys.map { |key| [I18n.t(key, scope: ["enums", "order", "status"]), key] }, {}, class: "form-control" %>
                  <%= f.submit "更新", class: "btn btn-success ml-3" %>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>

    <div class="col-9 mt-3">
      <table class="table table-lg">
        <thead>
          <tr class="table-secondary ">
            <th style="width: 20%;">商品名</th>
            <th style="width: 10%;">単価(税込)</th>
            <th style="width: 10%;">数量</th>
            <th style="width: 15%;">小計</th>
            <th style="width: 15%;">製作ステータス</th>
            <th style="width: 10%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %> 
            <%= form_with model: order_detail, url: admin_order_order_detail_path(@order, order_detail), method: :patch, local: true do |f| %>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= (order_detail.item.price*1.1).floor.to_s(:delimited) %></td>
                <td><%= order_detail.amount %></td>
                <td><%= (order_detail.item.price*1.1*order_detail.amount).floor.to_s(:delimited) %></td>
                <td>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |key| [I18n.t(key, scope: ["enums", "order_detail", "making_status"]), key] }, {}, class: "form-control" %>
                </td>
                <td><%= f.submit "更新", class: "btn btn-success ml-3" %></td> 
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table> 
    </div>
    <div class="col-3 mt-5">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td><strong>商品合計</strong></td>
            <td>
              <% total = 0 %>
                <% @order.order_details.each do |order_detail| %>
                  <% if order_detail.order_id == @order.id %>
                    <% total += (order_detail.item.price*1.1*order_detail.amount).floor %>
                  <% end %>
                <% end %>
              <%= total.to_s(:delimited) %>円
            </td>
          </tr>
          <tr>
            <td><strong>送料</strong></td>
            <td><%= @order.shipping_cost %>円</td>
          </tr>
          <tr>
            <td><strong>請求金額合計</strong></td>
            <td><strong><%= @order.total_payment.to_s(:delimited) %>円</strong></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>