config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  
  scope module: :public do
    root to: "homes#top"
    get "home/about"=>"homes#about"
    resources :items, only: [:index, :show]
    get "customers/my_page"=>"customers#show"
    get "customers/information/edit"=>"customers#edit"
    patch "customers/information"=>"customers#update"
    get "customers/unsubscribe"=>"customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do 
        get "complete"
        post "confirm"
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]{2,50}\z/, message: 'は２文字以上の全角のひらがな、カタカナ、漢字のみで入力してください。' }
  validates :postal_code, format: { with: /\A\d{7}\z/, message: 'は7桁の半角数字のみで入力してください。' }
  validates :address, presence: true, length: { maximum: 255 }
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :amount ,presence:true

  def subtotal
    item.with_tax_price * amount
  end
  # 小計を求めるメソッド

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, :first_name, format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]{1,20}\z/, message: 'は１字以上の全角のひらがな、カタカナ、漢字のみで入力してください。' }

  validates :last_name_kana, :first_name_kana, format: {with: /\A[ァ-ヶー]+\z/, message: 'は１字以上の全角カタカナで入力して下さい。' }

  validates :postal_code, format: { with: /\A\d{7}\z/, message: 'は7桁の半角数字のみで入力してください。' }
  
  validates :address, length: { maximum: 255 }, presence:{ message: 'は必須項目です。' }

  validates :telephone_number, format: { with: /\A\d{10,11}\z/, message: 'は10桁または11桁の半角数字のみで入力してください。' }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, length: { minimum: 1, maximum: 50, message: 'を入力してください。' }
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  validates :image, presence: { message: 'のファイルを選択してください' }
  validates :name, length: { minimum: 1, maximum: 50, message: 'は必須項目です。' }
  validates :introduction, presence:true, length: {maximum: 200}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :is_active, inclusion: { in: [true, false] }

  def with_tax_price
    (price * 1.1).floor
  end
  # 消費税を求めるメソッド

  TAX_RATE = 0.1
    def tax_included_price
    (price * (1 + TAX_RATE)).round
    end

    def status_label
      is_active ? "販売中" : "販売停止中"
    end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {
    credit_card: 0,
    transfer: 1 
  }

  enum status: {
    waiting_for_payment: 0, # 入金待ち (デフォルト)
    payment_confirmed: 1,   # 入金確認
    in_production: 2,       # 製作中
    ready_to_ship: 3,       # 製作完了
    shipped: 4              # 発送済み
  }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :name, format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]{2,20}\z/, message: 'は２文字以上の全角のひらがな、カタカナ、漢字のみで入力してください。' }
  validates :postal_code, format: { with: /\A\d{7}\z/, message: 'は7桁の半角数字のみで入力してください。' }
  validates :address, presence: true, length: { maximum: 255 }
  validates :payment_method, presence: true


  def subtotal
    item.with_tax_price * amount
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: {
    unable_to_start: 0, # 着手不可(デフォルト)
    not_started: 1,    # 製作待ち
    in_production: 2,  # 製作中
    completed: 3       # 製作完了
  }

  belongs_to :order
  belongs_to :item
  
  before_create :set_default_making_status
  after_update :update_order_status

  private
    def set_default_making_status
      self.making_status ||= :unable_to_start
    end
    
    def update_order_status
      order = self.order
      if order.order_details.any? { |detail| detail.in_production? }
        order.update(status: :in_production)
      elsif order.order_details.all? { |detail| detail.completed? }
        order.update(status: :ready_to_ship)
      end
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "正常に登録されました"
    else
      render:index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "変更が保存されました"
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品が正常に登録されました"
    else
      render:new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice:"変更が保存されました"
    else
      render:edit
    end
  end

private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <ul style="list-style-type: none;">
      <% resource.errors.full_messages.each do |message| %>
        <li>
          <span class="text-white bg-danger rounded"><%= message %></span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'notice' %>
  <div class="alert alert-success alert-dismissible">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% elsif message_type == 'alert' %>
    <div class="alert alert-danger alert-dismissible">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="float: left;">ながのCAKE<br>
    〒xxx-xxxx 長野県xx市xx111-11 tel:xxxx-xx-xxxx
  </p>
  <p class="float: right;">ⒸCopyRight Team Mc.inc</p>
</footer>

app/views/layouts/_header_admin.html.erb
<header class="header">
  <div class="container">
    <div class="row">
    <a href="/admin" class="col-auto">
      <%= image_tag "ながのCAKE.PNG", alt: "ながのCAKEロゴ", style: "width: 150px; height: 150px;" %>
    </a>

  <nav class="col">
    <ul class="nav-list">
      <% if admin_signed_in? %>
        <li class="nav-list-item">
          <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %>
        </li>
      <% else %>
        <li class="nav-list-item">
          <%= link_to "About", home_about_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
        </li>
      <% end %>
    </ul>
    </nav>
  </div>
  </div>
</header>

app/views/layouts/_header_public.html.erb
<header class="header">
  <div class="container">
    <div  class="row">
    <a href="/" class="col-auto">
      <%= image_tag "ながのCAKE.PNG", alt: "ながのCAKEロゴ", style: "width: 150px; height: 150px;" %>
    </a>

<div class="mt-3 mr-5 text-black">
  <% if customer_signed_in? %>
    ようこそ、<%= current_customer.last_name %>さん！
  <% end %>
</div>

  <nav class="col">
    <ul class="nav-list">
      <% if customer_signed_in? %>
        <li class="nav-list-item">
          <%= link_to "マイページ", customers_my_page_path(current_customer), class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %>
        </li>
      <% else %>
        <li class="nav-list-item">
          <%= link_to "About", home_about_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
        </li>
        <li class="nav-list-item">
          <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
        </li>
      <% end %>
    </ul>
    </nav>
  </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ed90dd2909.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if admin_signed_in? %>
        <%= render "layouts/header_admin" %>
      <% else %>
        <%= render "layouts/header_public" %>
      <% end %>

      <main class="content">
        <%= render "layouts/flash_message" %>
        <%= yield %>
      </main>
    </div>
    
    <%= render "layouts/footer" %>
  </body>
</html>